### ISSUE TITLE
Does this work for C-Series as well?

### ISSUE THREAD

**Issue by TonyG-SFLVMUG** [FooBartn/vCheck-UCS#4]
I was wondering if this script will work on c-series servers as well as b-series. I have one environment that I am trying to run this on that has C-series and it does not work yet works perfectly fine on the B-series.

**Comment by FooBartn** [comment]
Which particular part are you referencing? It should work for anything in a single UCS domain. I will gladly take a look at any plugin that is functioning unexpectedly.

Thanks!

**Comment by TonyG-SFLVMUG** [comment]
I guess what I am asking is what if this is not in a domain and is a stand alone.

**Comment by FooBartn** [comment]
Ah! I apologize, this is currently only for UCS domains. All of the plugins use the UCSM Powertool module, not the one for standalone C series.

Is there anything in particular you wanted to be able to check on your c series? Perhaps I could help?

**Comment by TonyG-SFLVMUG** [comment]
I guess what I am looking to do is get some form of report that I can setup to do a quick 1 page overview of the environment. Something to keep my admins from spending too much time logging into all of these standalones.

**Comment by FooBartn** [comment]
Have you taken a look at the IMC supervisor 2.x? It's unfortunately still something to log into, but it's one location vs multiple with some added benefits. To my knowledge it currently doesn't have a Powertool associated, but it does have a rest api.

**Comment by FooBartn** [comment]
Hey Tony

Since this particular script isn't meant to address standalone servers, I'm going to go ahead and close it. You're welcome to hit me up on twitter if I can help you with anything.

Thanks for checking out the script!
